Repository sendgrid/ui-components, pull requests merged in 2018-10, with the labels that each got.

#290 Update contributing doc w/ component organization #patch
  CHANGELOG.md
  CONTRIBUTING.md
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#292 Add line breaks to contributing doc #patch
  CONTRIBUTING.md
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#291 Style Guide 1.10.8 updates #patch
  CHANGELOG.md
  src/styles/email-card.module.scss
  src/styles/segment-term.module.scss
  test_image/__image_snapshots__/image-storyshots-ts-image-storyshots-email-card-email-card-with-actions-1-snap.png
Labels: HacktoberFest, difficulty: medium, status: hacktoberfest approved

#298 MCFE-993: add supported file extensions prop to file upload
  src/csv-upload.tsx
  src/file-upload.tsx
Labels: status: code review request

#299 MCFE-993 #fix: check for null file name
  src/file-upload.tsx
Labels: status: code review request

#276 Updated readme formatting
  README.md
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#284 Use Portable Bash Shebang
  copyStyles.sh
  imageSnapshot.sh
  updateIconTypes.sh
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#293 add sendgrid logo and contibutor count and twitter follow
  README.md
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#300 Corrected typos and spelling errors in README files
  .buildkite/README.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE/bug.md
  README.md
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#296 Move GitHub templates to ".github" folder
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/new-component-proposal.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved, status: waiting for feedback

#301 MCFE-984: disable text input on color picker
  src/color-picker.tsx
  src/styles/color-picker.module.scss
  test/__snapshots__/Storyshots.test.ts.snap
  test_image/__image_snapshots__/image-storyshots-ts-image-storyshots-color-palette-color-picker-1-snap.png
Labels: status: code review request

#288 CHORE: Update README
  README.md
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#303 Update LICENSE
  LICENSE
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#302 Fixed license icon link on readme
  README.md
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#305 chore: update out of date css definition files
  packages/ui-components/text-input.d.ts
  src/styles/alert.module.scss.d.ts
  src/styles/dropdown.module.scss.d.ts
  src/styles/email-card.module.scss.d.ts
  src/styles/segment-term.module.scss.d.ts
Labels: HacktoberFest, difficulty: easy, status: code review request, status: hacktoberfest approved

#304 Color picker with disabled text
  src/color-palette/index.tsx
  src/color-picker.tsx
  src/styles/color-palette.module.scss
  src/styles/color-picker.module.scss
  stories/ColorPalette.stories.tsx
  test/__snapshots__/Storyshots.test.ts.snap
  test_image/__image_snapshots__/image-storyshots-ts-image-storyshots-color-palette-color-picker-1-snap.png
  test_image/__image_snapshots__/image-storyshots-ts-image-storyshots-color-palette-text-disabled-1-snap.png
Labels: HacktoberFest, difficulty: medium, status: code review request, status: hacktoberfest approved

#307 Fix: Errors caused in TextArea from additional "MaxHeight" attribute
  src/text-area.tsx
  test/__snapshots__/Storyshots.test.ts.snap
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#309 add license to readme
  README.md
Labels: HacktoberFest, difficulty: easy, status: hacktoberfest approved

#306 chore: Update PR template to be up to date
  .github/PULL_REQUEST_TEMPLATE.md
Labels: HacktoberFest, difficulty: easy, status: code review request
